name: Build and deploy Python project to Azure Function App - s-rag-tmp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Prepare deployment package'
      run: |
        mkdir deployment
        cp -r * deployment/
        rm -rf deployment/.git deployment/.github

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 's-rag-tmp'
        slot-name: 'Production'
        package: './deployment'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9ABF7F7166584172B4A6398CCF2BC2BF }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true